app:
  name: example-app
  repo_url: https://github.com/thebigbone/load-balancer
  directory: load-balancer
  language: go
  domain: example.com
  proxy: localhost:8090
  arguments:
    - "-port"
    - "8090"
